### ISSUE TITLE
Can not use with NextJS

### ISSUE THREAD

**Issue by matthiez** [sms77io/js-client#24]
Cannot read properties of undefined (reading 'from')

NextJS v15

**Comment by KaiKustermann** [comment]
I am having the same issue right now, using node 20 and @seven.io/client 3.0.0. Thank you for investigating this👍

**Comment by matthiez** [comment]
> I am having the same issue right now, using node 20 and @seven.io/client 3.0.0. Thank you for investigating this👍

Hi Kai,
this seems to do the trick:
`globalThis.JS_MD5_NO_NODE_JS = true`

It's related to this [issue](https://github.com/emn178/js-md5/issues/47).

**Comment by matthiez** [comment]
Please upgrade to v3.0.1.

**Comment by KaiKustermann** [comment]
Thank you, works well now :)
